pipeline {
    agent any

    environment {
        JAVA_HOME = "/usr/lib/jvm/java-17-openjdk-amd64"
        MAVEN_HOME = "/usr/share/maven"
        JAR_NAME = "jae_project-0.0.1-SNAPSHOT.jar"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Deploy') {
            when {
                branch 'main'
            }
            steps {
                script {
                    // Jenkins Credentials 사용
                    withCredentials([
                        string(credentialsId: 'frountIP', variable: 'FROUNT_IP'),
                        string(credentialsId: 'DB_ID', variable: 'DB_ID'),
                        string(credentialsId: 'DB_PW', variable: 'DB_PW'),
                        string(credentialsId: 'DB_IP', variable: 'DB_IP')
                    ]) {
                    	
                    	sh """
					    # application.yml 파일 내의 템플릿 변수들을 Jenkins Credentials 값으로 치환
					    sed -i "s#\\\${frountIP}#${FROUNT_IP}#" jae_project/src/main/resources/application.yml
					    sed -i "s#\\\${DB_ID}#${DB_ID}#" jae_project/src/main/resources/application.yml
					    sed -i "s#\\\${DB_PW}#${DB_PW}#" jae_project/src/main/resources/application.yml
					    sed -i "s#\\\${DB_IP}#${DB_IP}#" jae_project/src/main/resources/application.yml
    					"""
                    
                        // 빌드 단계 - 환경 변수 사용
                        dir('jae_project') {
                        sh """
                        ${MAVEN_HOME}/bin/mvn clean package  \
                        -DskipTests=true
                        """
						}
                         // 기존 프로세스 종료 단계
                        sh """
                        PID=\$(lsof -t -i:8081) || true
                        if [ ! -z "\$PID" ]; then
                            echo "Stopping existing application with PID: \$PID"
                            kill -9 \$PID
                        fi
                        """
                        
                        // 배포 단계
                        sh """
                        mv jae_project/target/*.jar /home/ubuntu/${JAR_NAME}
                        """
                        
                        // 새로운 애플리케이션 실행 단계
                        sh """
						nohup java -jar /home/ubuntu/${JAR_NAME} > /home/ubuntu/app.log 2>&1 &
						"""

                    }
                }
            }
        }
    }
}
